# Generated by Django 5.0.4 on 2024-05-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
        ('movimiento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seguimiento', models.CharField(max_length=6, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_envio', models.IntegerField(choices=[(1, 'Retiro en local'), (2, 'Envio a sucursal'), (3, 'Envio a domicilio')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Pagado'), (3, 'Rechazado'), (4, 'Cancelado'), (5, 'En preparacion'), (6, 'Despachado'), (7, 'Entregado')], default=1)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.direccion')),
                ('movimientos', models.ManyToManyField(to='movimiento.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
