# Generated by Django 5.0.4 on 2024-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_alter_transaccion_cod_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cod_seguimiento',
            field=models.CharField(default='D7E12C', max_length=6, unique=True),
        ),
    ]
