# Generated by Django 5.0.6 on 2024-06-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0025_alter_transaccion_cod_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cod_seguimiento',
            field=models.CharField(default='BF57A0', max_length=6, unique=True),
        ),
    ]
