# Generated by Django 5.0.4 on 2024-05-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('BUE', 'Buenos Aires'), ('CAT', 'Catamarca'), ('CHA', 'Chaco'), ('CHU', 'Chubut'), ('CBA', 'Córdoba'), ('COR', 'Corrientes'), ('ERI', 'Entre Ríos'), ('FOR', 'Formosa'), ('JUJ', 'Jujuy'), ('LP', 'La Pampa'), ('LR', 'La Rioja'), ('MZA', 'Mendoza'), ('MIS', 'Misiones'), ('NEU', 'Neuquén'), ('RNE', 'Río Negro'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SDE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego'), ('TUC', 'Tucumán'), ('CF', 'Capital Federal')], default='BUE', max_length=3)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=8)),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('depto', models.CharField(max_length=3, null=True)),
                ('piso', models.IntegerField(null=True)),
                ('observaciones', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
