# Generated by Django 5.0.6 on 2024-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='depto',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
