# Generated by Django 5.0.4 on 2024-06-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('change_cliente_activo', 'Can change cliente and activo status')]},
        ),
    ]
