# Generated by Django 5.0.4 on 2024-06-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('change_cliente_activo', 'Can change cliente and activo status')]},
        ),
    ]
