# Generated by Django 5.0.4 on 2024-05-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('foto_prod', models.ImageField(null=True, upload_to='calzado/')),
                ('descripcion', models.TextField()),
                ('color', models.IntegerField(choices=[(1, 'Blanco'), (2, 'Negro'), (3, 'Marron'), (4, 'Beige'), (5, 'Rojo'), (6, 'Azul'), (7, 'Amarillo'), (8, 'Naranja'), (9, 'Verde'), (10, 'Violeta'), (11, 'Gris'), (12, 'Rosa'), (13, 'Celeste'), (14, 'Crema'), (15, 'Nude'), (16, 'Plateado'), (17, 'Dorado'), (18, 'Multicolor')], default=1)),
                ('material', models.IntegerField(choices=[(1, 'Gamuza'), (2, 'Cuero'), (3, 'Cuero sintetico'), (4, 'Charol'), (5, 'Ecocuero'), (6, 'Lona'), (7, 'Algodon'), (8, 'Corderito'), (9, 'Engomado'), (10, 'Gabardina'), (11, 'PVC')], default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_calzado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.tipo')),
            ],
        ),
    ]
