# Generated by Django 5.0.4 on 2024-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calzado', '0002_alter_calzado_foto_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='color',
            field=models.IntegerField(choices=[(1, 'Blanco'), (2, 'Negro'), (3, 'Marron'), (4, 'Beige'), (5, 'Rojo'), (6, 'Azul'), (7, 'Amarillo'), (8, 'Naranja'), (9, 'Verde'), (10, 'Violeta'), (11, 'Gris'), (12, 'Rosa'), (13, 'Celeste'), (14, 'Crema'), (15, 'Nude'), (16, 'Plateado'), (17, 'Dorado'), (18, 'Multicolor'), (19, 'Tostado'), (20, 'Bordó')], default=1),
        ),
        migrations.AlterField(
            model_name='calzado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
