# Generated by Django 5.0.4 on 2024-05-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calzado', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('talle', models.IntegerField(choices=[(36, 36), (37, 37), (38, 38), (39, 39), (40, 40)], default=36)),
                ('cantidad', models.IntegerField(default=0)),
                ('motivo', models.IntegerField(choices=[(1, 'VENTA'), (2, 'STOCK')], default=1)),
                ('activo', models.BooleanField(default=True)),
                ('calzado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calzado.calzado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
