# Generated by Django 5.0.6 on 2024-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
