# Generated by Django 5.0.4 on 2024-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0002_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
