# Generated by Django 5.0.4 on 2024-06-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0003_movimiento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
